simulation:
  steps: 50
  poisson_lambda: 0.5

machines:
  - id: M1
    equipment: 
      - 1
      - 2
      - 3
      - 4
    energy: 1000
  - id: M2
    equipment:
      - 1
      - 2
      - 3
      - 4
    energy: 800

tasks:
  - id: T1
    required_equipment: 1
    energy_cost: 15
  - id: T2
    required_equipment: 2
    energy_cost: 10