dat: Датчики внешней информации {
    dist: Дистанционные {
        vis: Визуальные (машинного видения) {
            l:|md
            - Лазерные дальномеры (лидары)
            - Радары
            - Инфракрасные датчики
            - Time-of-flight-камеры
            - Стерео-камеры
            - Пленоптические камеры
            |
        }

        lok: Локационные {
            s: |md
            - Струйные
            - Магнитные
            - Индукционные
            - Светолокационные
            - Ультразвуковые
            - Лазерные
            |
        }
    }

    kont: Контактные {
        t: |md
        - Тактильные
        - Перемещения
        - Усилия
        - Давления
        |
    }
}